# Generated by Django 5.1.2 on 2025-04-25 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_avatar_alter_bike_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='guides/resumes/', verbose_name='Резюме'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='experience',
            field=models.IntegerField(verbose_name='Опыт работы (лет)'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='languages',
            field=models.CharField(max_length=200, verbose_name='Знание языков'),
        ),
    ]
