# Generated by Django 5.1.2 on 2025-04-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    """Миграция для добавления поля profile_url гиду."""

    dependencies = [
        ('main', '0003_guide_resume_alter_guide_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='profile_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на профиль'),
        ),
    ]
