# Generated by Django 5.1.2 on 2025-05-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    """Миграция для изменения опций тура и локации."""

    dependencies = [
        ('main', '0004_guide_profile_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'Маршрут', 'verbose_name_plural': 'Маршруты'},
        ),
        migrations.AlterField(
            model_name='tour',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
    ]
