# Generated by Django 5.1.2 on 2025-05-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_tour_options_alter_tour_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='tours',
            field=models.ManyToManyField(related_name='guides', through='main.GuideTour', to='main.tour'),
        ),
    ]
