# Generated by Django 5.1.2 on 2025-05-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    """Миграция для добавления поля активности тура."""

    dependencies = [
        ('main', '0008_alter_tour_options_alter_bike_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
