# Generated by Django 5.1.2 on 2025-05-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    """Миграция для добавления изображения к туру."""

    dependencies = [
        ('main', '0009_tour_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tours/', verbose_name='Изображение'),
        ),
    ]
