# Generated by Django 4.2 on 2025-06-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    """Миграция для добавления времени начала тура."""

    dependencies = [
        ('main', '0010_tour_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время начала экскурсии'),
        ),
    ]
