# Generated by Django 4.2 on 2025-06-22 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_tour_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Забронировано')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='main.guide', verbose_name='Гид')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='main.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Слот экскурсии',
                'verbose_name_plural': 'Слоты экскурсий',
                'ordering': ['datetime'],
            },
        ),
    ]
