# Generated by Django 4.2 on 2025-06-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Пользователь', 'Пользователь'), ('Гид', 'Гид'), ('Менеджер', 'Менеджер'), ('Администратор', 'Администратор')], default='Пользователь', max_length=50, verbose_name='Роль'),
        ),
    ]
