# Generated by Django 4.2 on 2025-06-24 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='bike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='main.bike', verbose_name='Велосипед'),
        ),
    ]
